# Generated by Django 2.2.6 on 2019-11-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_desc',
            new_name='author',
        ),
    ]
