# Generated by Django 2.2.6 on 2019-11-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191112_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=64, verbose_name='автор'),
        ),
    ]
